program TerraSoft;

uses
  Forms,
  unPrincipal in 'unPrincipal.pas' {frmPrincipal},
  unConsultas in 'unConsultas.pas' {frmConsultas},
  unDM in 'unDM.pas' {DM: TDataModule},
  UnClientes in 'UnClientes.pas' {frmClientes},
  unCadastros in 'unCadastros.pas' {frmCadastros},
  unIncluirCliente in 'unIncluirCliente.pas' {frmIncluirCliente},
  unFuncoes in 'unFuncoes.pas',
  unMunicipios in 'unMunicipios.pas' {frmMunicipios},
  unIncluirMunicipio in 'unIncluirMunicipio.pas' {frmIncluirMunicipio},
  unRegioes in 'unRegioes.pas' {frmRegioes},
  unIncluirRegioes in 'unIncluirRegioes.pas' {frmIncluirRegioes},
  unFornecedores in 'unFornecedores.pas' {frmFornecedores},
  unIncluirFornecedor in 'unIncluirFornecedor.pas' {frmIncluirFornecedor},
  unFuncionarios in 'unFuncionarios.pas' {frmFuncionarios},
  unIncluirFuncionario in 'unIncluirFuncionario.pas' {frmIncluirFuncionario},
  unIncluirProduto in 'unIncluirProduto.pas' {frmIncluirProduto},
  unIncluirServico in 'unIncluirServico.pas' {frmIncluirServico},
  unServicos in 'unServicos.pas' {frmServicos},
  unIncluirEquipamento in 'unIncluirEquipamento.pas' {frmIncluirEquipamento},
  unEquipamentos in 'unEquipamentos.pas' {frmEquipamentos},
  unIncluirFormaPgto in 'unIncluirFormaPgto.pas' {frmIncluirFormaPgto},
  unFormasPgto in 'unFormasPgto.pas' {frmFormasPgto},
  unIncluirCondicaoPgto in 'unIncluirCondicaoPgto.pas' {frmIncluirCondicaoPgto},
  unCondicoesPgto in 'unCondicoesPgto.pas' {frmCondicoesPgto},
  unOS in 'unOS.pas' {frmOS},
  unIncluirOS in 'unIncluirOS.pas' {frmIncluirOS},
  unFaturamentoOS in 'unFaturamentoOS.pas' {frmFaturamentoOS},
  unContasReceber in 'unContasReceber.pas' {frmContasReceber},
  unIncluirContasReceber in 'unIncluirContasReceber.pas' {frmIncluirContasReceber},
  unIncluirPlanoContas in 'unIncluirPlanoContas.pas' {frmIncluirPlanoContas},
  unPlanoContas in 'unPlanoContas.pas' {frmPlanoContas},
  unQuitarContaReceber in 'unQuitarContaReceber.pas' {frmQuitarContaReceber},
  unIncluirConta in 'unIncluirConta.pas' {frmIncluirConta},
  unContas in 'unContas.pas' {frmContas},
  unHistoricoContaReceber in 'unHistoricoContaReceber.pas' {frmHistoricoContaReceber},
  unCaixa in 'unCaixa.pas' {frmCaixa},
  unIncluirCaixa in 'unIncluirCaixa.pas' {frmIncluirCaixa},
  UnSelecaoContaAvista in 'UnSelecaoContaAvista.pas' {frmSelecaoContaAvista},
  unManutencoes in 'unManutencoes.pas' {frmManutencoes},
  unFaturamentoManu in 'unFaturamentoManu.pas' {frmFaturamentoManu},
  unAgendaManu in 'unAgendaManu.pas' {frmAgendaManu},
  unIncluirAgendamento in 'unIncluirAgendamento.pas' {frmIncluirAgendamento},
  unConsultaManutencoes in 'unConsultaManutencoes.pas' {frmConsultaManutencoes},
  unContasPagar in 'unContasPagar.pas' {frmContasPagar},
  unIncluirContasPagar in 'unIncluirContasPagar.pas' {frmIncluirContasPagar},
  unQuitarContaPagar in 'unQuitarContaPagar.pas' {frmQuitarContaPagar},
  unHistoricoContaPagar in 'unHistoricoContaPagar.pas' {frmHistoricoContaPagar},
  unSelecaoRelatorios in 'unSelecaoRelatorios.pas' {frmSelecaoRelatorios},
  unSelecaoRelFornecedores in 'unSelecaoRelFornecedores.pas' {frmSelecaoRelFornecedores},
  unRelContasPagar in 'unRelContasPagar.pas' {frmRelContasPagar},
  unRelContasReceber in 'unRelContasReceber.pas' {frmRelContasReceber},
  unRelOS in 'unRelOS.pas' {frmRelOS},
  unRelacaoOS in 'unRelacaoOS.pas' {frmRelacaoOS},
  unIncluirSubPlanoContas in 'unIncluirSubPlanoContas.pas' {frmIncluirSubPlanoContas},
  unSubPlanosdeContas in 'unSubPlanosdeContas.pas' {frmSubPlanosdeContas},
  unReciboCR in 'unReciboCR.pas' {frmReciboCR},
  unRelCaixa in 'unRelCaixa.pas' {frmRelCaixa},
  unSobre in 'unSobre.pas' {frmSobre},
  unIncluirEmpresa in 'unIncluirEmpresa.pas' {frmIncluirEmpresa},
  unEmpresas in 'unEmpresas.pas' {frmEmpresa},
  unReciboCP in 'unReciboCP.pas' {frmReciboCP},
  unConfiguracoes in 'unConfiguracoes.pas' {frmConfiguracoes},
  unLavacoes in 'unLavacoes.pas' {frmLavacoes},
  unIncluirLavacao in 'unIncluirLavacao.pas' {frmIncluirLavacao},
  unRenegociarCP in 'unRenegociarCP.pas' {frmRenegociarCP},
  unRenegociarCR in 'unRenegociarCR.pas' {frmRenegociarCR},
  unIncluirTipoCobranca in 'unIncluirTipoCobranca.pas' {frmIncluirTipoCobranca},
  unTiposCobrancas in 'unTiposCobrancas.pas' {frmTiposCobrancas},
  unEntradasCompras in 'unEntradasCompras.pas' {frmEntradasCompras},
  unVisualizarFatManu in 'unVisualizarFatManu.pas' {frmVisualizarFatManu},
  unRelatoriosManutencoes in 'unRelatoriosManutencoes.pas' {frmRelatoriosManutencoes},
  unRelEquipamentos in 'unRelEquipamentos.pas' {frmRelEquipamentos},
  GerarBackup in 'GerarBackup.pas' {FGerarBackup},
  Principal in 'Principal.pas' {frmBackup},
  RestaurarBackup in 'RestaurarBackup.pas' {FRestaurarBackup},
  unUsuarios in 'unUsuarios.pas' {frmUsuarios},
  unIncluirUsuario in 'unIncluirUsuario.pas' {frmIncluirUsuario},
  unIncluirTela in 'unIncluirTela.pas' {frmIncluirTela},
  unBotoes in 'unBotoes.pas' {frmBotoes},
  unIncluirBotao in 'unIncluirBotao.pas' {frmIncluirBotao},
  unTelas in 'unTelas.pas' {frmTelas},
  unPermissoesUsuarios in 'unPermissoesUsuarios.pas' {frmPermissoesUsuarios},
  unOrdensParcelaOrigem in 'unOrdensParcelaOrigem.pas' {frmOrdensParcelaOrigem},
  unLogin in 'unLogin.pas' {frmLogin},
  unTransferenciaCaixa in 'unTransferenciaCaixa.pas' {frmTransferenciaCaixa},
  unServicosRealizadosPorFuncionario in 'unServicosRealizadosPorFuncionario.pas' {frmServicosRealizadosPorFuncionario},
  unRelServicosRealizadosPorFuncionario in 'unRelServicosRealizadosPorFuncionario.pas' {frmRelServicosRealizadosPorFuncionario},
  unProdutos in 'unProdutos.pas' {frmProdutos},
  unConstTelas in 'unConstTelas.pas',
  unSelRelServicosEquipamentos in 'unSelRelServicosEquipamentos.pas' {frmSelRelServicosEquipamentos},
  unRelServicosRealizadosPorEquipamento in 'unRelServicosRealizadosPorEquipamento.pas' {frmRelServicosRealizadosPorEquipamento},
  unCreditosCliente in 'unCreditosCliente.pas' {frmCreditosCliente},
  unIncluirCreditosCliente in 'unIncluirCreditosCliente.pas' {frmIncluirCreditosCliente},
  unAbastecimentos in 'unAbastecimentos.pas' {frmAbastecimentos},
  unTiposCombustiveis in 'unTiposCombustiveis.pas' {frmTiposCombustiveis},
  unIncluirTipoCombustivel in 'unIncluirTipoCombustivel.pas' {frmIncluirTipoCombustivel},
  unIncluirAbastecimento in 'unIncluirAbastecimento.pas' {frmIncluirAbastecimento},
  unCompras in 'unCompras.pas' {frmCompras},
  unIncluirCompra in 'unIncluirCompra.pas' {frmIncluirCompra};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'TerraplenSoft';
  Application.CreateForm(TDM, DM);
  Application.Run;
end.
